### PR TITLE
Change Base.similar and support unsafe_convert for ElasticArray

### LINKED ISSUE #4: Should Base.similar be overridden?
I'm not a fan of 6fcfa52e54.  With this change, multiplying an `ElasticArray` matrix by a regular matrix results in an `ElasticArray`, not a `Matrix`.  Chances are, if I am performing an operation on an `ElasticArray`, I am looking for it to return a non-elastic array.  I think it is non-standard to override `Base.similar` in this way.

### PR DESCRIPTION
**Pull request by oschulz**
Fixes #4.

### CODE REVIEW

**Comment by oschulz** [comment]
Fixes #5.

**Comment by oschulz** [comment]
@garrison, could you give this a try?

**Comment by garrison** [comment]
It works perfectly for me.  Thanks!  (Also, in the future it may also be good to have some explicit tests for common operations, such as matrix multiplication.)

**Comment by oschulz** [comment]
Good idea - will do.

**Pull request merged**
