### PR TITLE
overhaul constructors

### PR DESCRIPTION
**Pull request by colinxs**
Following the implementation of `Array`:

1. Adds `undef` constructor with size specified as a `Tuple`
2. Adds constructors that allow type parameters to be specified
3. Defines `convert` in terms of the above.

### CODE REVIEW

**Comment by colinxs** [comment]
@oschulz I've been using ElasticArrays.jl quite a bit but ran into a few oddities. I ended up copying out `ElasticArray` to a [package I use internally](https://github.com/Lyceum/SpecialArrays.jl/blob/master/src/elasticarray.jl) and fixing things there because it was easiest at the time, but I was hoping to port those changes back to ElasticArrays.jl. For the sake of laziness would you mind if the remaining changes came rolled up into one PR?

**Comment by oschulz** [comment]
> For the sake of laziness would you mind if the remaining changes came rolled up into one PR

Sure, should still be possible to understand what you did. Are the changes non-breaking?

**Comment by oschulz** [comment]
Btw, @colinxs, if you use ElasticArrays.jl (glad that you like it and want to help improve it!) in an array-of-arrays semantic context, you may also be interested in ArraysOfArrays.jl.

**Comment by oschulz** [comment]
A primary design goal for `ElasticArray` was actually to act as a backend for `ArraysOfArrays.ArrayOfSimilarArrays`.

**Comment by colinxs** [comment]
@oschulz 

> Sure, should still be possible to understand what you did. Are the changes non-breaking?

Awesome! I'll at least break up the commits so it's easier to parse. Everything should be non-breaking except for support for broadcasting that I added and which I'll put in a separate PR.

> Btw, @colinxs, if you use ElasticArrays.jl (glad that you like it and want to help improve it!) in an array-of-arrays semantic context, you may also be interested in ArraysOfArrays.jl.

I'm actually already a fan of ArraysOfArrays.jl :). I was the one who opened https://github.com/oschulz/ArraysOfArrays.jl/issues/2 awhile back. In case you missed it, I recently posted a solution to that PR.

**Comment by oschulz** [comment]
Sounds, great, thanks for lending a hand!

>  I was the one who opened oschulz/ArraysOfArrays.jl#2 awhile back

Oh, right, that was you! Sorry, wanted to get that done a long time ago, was just overloaded.

**Pull request merged**
